name: kenso
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^4.5.6
  eva_icons_flutter: ^3.0.2
  firebase_core : ^0.5.2
  circle_bottom_navigation: ^1.0.6
  cloud_firestore: ^0.14.3
  image_picker: ^0.6.0+2
  geolocator: 5.0.1
  uuid: ^2.2.2
  path_provider: ^0.5.0+1
  image: ^2.0.7
  firebase_storage: ^5.0.1
  cached_network_image: ^2.0.0
  animator: ^2.0.1
  timeago: 2.0.28

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
    - family: Alegreya
      fonts:
        - asset: assets/fonts/AlegreyaSans-Regular.ttf
  assets:
    - assets/images/defaultUser.png
    - assets/images/search.png
    - assets/images/upload.png
