name: kenso
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^4.5.6
  eva_icons_flutter: ^3.0.2
  firebase_core : ^0.5.2
  circle_bottom_navigation: ^1.0.6
  cloud_firestore: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
  assets:
    - assets/images/defaultUser.png
    - assets/images/search.png
